rds_name = "rdsmoduleinstance1"
add_tags = {
  tag1 = "test"
  tag2 = "cloudtitans"
}
maintainer_service = "titanstest"
product_name       = "titanstest"
env_workspace      = "sandbox"
data_class         = "internal_use"
database_name      = "rdsmoduledb"
eng_version        = "13"
inst_class         = "db.r5.large"
maint_window       = "Mon:07:00-Mon:10:00"
ro_instance_count  = "1"
instance_ct        = "1"
ro_instance_class  = "db.r5.large"