# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Cd
      run: cd /home/runner/work/gha/gha
    - name: Build
      run: go mod init unittesting-terratest
 
    - name: Build2

      run: go mod tidy

    - name: Test

      run: cd /home/runner/work/gha/gha/Unit-Testing-rds-aurora-postgres/;go test -timeout 1h -v
